clear all
close all
clc

board=Board
board.movePiece(board,'e2e4')
board.movePiece(board,'e7e5')
board.movePiece(board,'f1d3')
board.movePiece(board,'a7a5')
board.movePiece(board,'g1f3')
board.movePiece(board,'b7b5')
board.movePiece(board,'e1g1')
board.movePiece(board,'a2a4')
board.movePiece(board,'b5a4')
board.movePiece(board,'a1a3')
board.movePiece(board,'h7h5')
board.movePiece(board,'a3b3')
board.movePiece(board,'a4a3')
board.movePiece(board,'b3b4')
board.movePiece(board,'a3a2')
board.movePiece(board,'b4b5')
board.movePiece(board,'a2a1')
board.movePiece(board,'b1a3')
board.movePiece(board,'a1c1')
board.movePiece(board,'d1e2')
board.movePiece(board,'c1f1')
board.movePiece(board,'e2e3')
board.movePiece(board,'f8e7')
board.movePiece(board,'e3g5')
board.movePiece(board,'e7f6')
board.movePiece(board,'g5g7')
board.movePiece(board,'f6h4')
board.movePiece(board,'g7f8')
board.movePiece(board,'h4f2')
